SWE: Mitschriften 07.12.2020
importPI19fromDHGE/dhge-pi19-sem3 pull request #101
Opened 2020-12-07 10:15 UTC by RvNovae

2020-12-07 10:15 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/SWE/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/DBS/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/RES/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/PRO/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/NET/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- SWE/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2020-12-07 20:37 UTC, ZeroPointMax approved these changes
sieht gut aus 👍

2020-12-07 20:41 UTC, ZeroPointMax reviewed
see #103

2020-12-08 17:42 UTC, ZeroPointMax requested changes
ich merge jetzt #102 hier rein

2020-12-08 17:44 UTC, sthinbetween approved these changes

2020-12-08 18:10 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/SWE/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/DBS/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/RES/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/PRO/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/NET/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- SWE/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2020-12-08 18:19 UTC, ZeroPointMax commented
@Steve2955 @photovoltex da ich hier mit rumgerührt habe, bin ich biased was das Approval angeht. Könnt ihr bitte prüfen, dass alles korrekt ist?

2020-12-08 20:04 UTC, photovoltex requested changes
siehe Kommentare:) sonst passt es meinerseits

2020-12-08 20:04 UTC, photovoltex commented on SWE/README.md
> +- Eigenschaft: nicht eindeutige Darstelleung $\Rightarrow$ Begleit-Text wird notwendig
`Darstelleung` typo

2020-12-08 21:24 UTC, ZeroPointMax commented on SWE/README.md
> +<<<<<<< HEAD
Haiaiai

2020-12-08 21:55 UTC, photovoltex approved these changes

2020-12-09 04:59 UTC, RvNovae commented
@ZeroPointMax du müsstest nochmal approven. Dann könntest du wahrscheinlich auch direkt mergen.

2020-12-09 11:50 UTC, ZeroPointMax approved these changes

2020-12-09 11:50 UTC, merged