SWE-sthinbetween-20201207
importPI19fromDHGE/dhge-pi19-sem3 pull request #102
Opened 2020-12-07 10:16 UTC by sthinbetween

2020-12-07 10:17 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/SWE/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/DBS/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/RES/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/PRO/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/NET/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- SWE/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2020-12-08 17:41 UTC, ZeroPointMax requested changes
ich merge das jetzt in #101 rein

2020-12-08 17:46 UTC, sthinbetween commented
> 
> 
> ich merge das jetzt in #101 rein
danke 👍

2020-12-08 17:48 UTC, sthinbetween commented
@ZeroPointMax schau aber bitte mal nach, es sieht so aus, als sei hier auch der eine NET commit mit drin, in dem wieder die .png Flies fehlen. Nicht dass wir uns die wieder löschen.

2020-12-08 18:11 UTC, ZeroPointMax commented
@sthinbetween scheint geklappt zu haben :)

2020-12-08 18:57 UTC, RvNovae commented
Wollen wir den hier PR dann schließen?

2020-12-08 21:23 UTC, ZeroPointMax commented
@RvNovae wäre sinnvoll xD

2020-12-08 21:23 UTC, closed without merging