SWE-oliver 10.12.2020
importPI19fromDHGE/dhge-pi19-sem3 pull request #108
Opened 2020-12-10 10:07 UTC by RvNovae

Das waren ... viele Bilder heute 😅

2020-12-10 10:08 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/SWE/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/DBS/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/RES/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/PRO/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/NET/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- SWE/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2020-12-11 11:35 UTC, ZeroPointMax requested changes
Ein kleiner Typo, ansonsten find ich es gut. Danke dir 👍

2020-12-11 11:35 UTC, ZeroPointMax commented on SWE/README.md
> +- ein ausgemalter Kreis mit Umrandung kennzeichnet dasd Ende
```suggestion
- ein ausgemalter Kreis mit Umrandung kennzeichnet das Ende
```

"dasd"

2020-12-11 16:05 UTC, ZeroPointMax approved these changes

2020-12-13 10:16 UTC, sthinbetween approved these changes

2020-12-13 12:32 UTC, merged