NET-sthinbetween-20201210
importPI19fromDHGE/dhge-pi19-sem3 pull request #110
Opened 2020-12-10 16:58 UTC by sthinbetween

Der letzte inhaltliche PR für dieses Semester!

2020-12-10 17:02 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/NET/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/DBS/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/RES/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/PRO/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/SWE/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- NET/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2020-12-10 18:24 UTC, RvNovae requested changes
Typos und ein paar kleinere Anmerkungen. 

Ansonsten sehr ausführlich, vielen Dank!

2020-12-10 18:24 UTC, RvNovae commented on NET/README.md
> +- Verteilt vorhandene Konfigurationen (abgelegt in der „Control-Plane“) müssen konsistent sein
Fehlt hier vielleicht ein Komma, Pfeil o.Ä? 
```suggestion
- Verteilt vorhandene Konfigurationen (abgelegt in der „Control-Plane“) $\rightarrow$ müssen konsistent sein
```

2020-12-10 18:24 UTC, RvNovae commented on NET/README.md
> +- Interaktion mittels Packet-In- und Packet-Out-Nachricht verdeutlicht diedetaillierte Kontrolle, die der Controller über die Abläufe im Netzwerk besitzt
```suggestion
- Interaktion mittels Packet-In- und Packet-Out-Nachricht verdeutlicht die detaillierte Kontrolle, die der Controller über die Abläufe im Netzwerk besitzt
```

2020-12-10 18:24 UTC, RvNovae commented on NET/README.md
> +  - VTEP sorgt dafür, dass die von der VM versendeten Pakete an diejenigen physischen Maschinen weitergeleitet werden, die auch VM´s des selben logischen VxLANs haben
```suggestion
  - VTEP sorgt dafür, dass die von der VM versendeten Pakete an diejenigen physischen Maschinen weitergeleitet werden, die auch VMs des selben logischen VxLANs haben 
```

2020-12-10 18:24 UTC, RvNovae commented on NET/README.md
> +3. VTEP der physischen Maschine, die die adressierte VM ausführt, nimmt UDP-Paket entgegen und entfernt die ergänzten Header, so dass nur das ursprüngliche Ethernet-Frame bleibt
```suggestion
3. VTEP der physischen Maschine, die die adressierte VM ausführt, nimmt UDP-Paket entgegen und entfernt die ergänzten Header so, dass nur das ursprüngliche Ethernet-Frame bleibt
```

2020-12-10 18:24 UTC, RvNovae commented on NET/README.md
> +- VTEP speichert eine Abbildung der Quell-MAC-Adresse des gekapselten Ethernet-Frames und der Quell-IP-Adresse des kapselnden IP-Headers $\rightarrow$ Antwort an MAC-Adresse kann mittels IP-Unicast r
```suggestion
- VTEP speichert eine Abbildung der Quell-MAC-Adresse des gekapselten Ethernet-Frames und der Quell-IP-Adresse des zu kapselnden IP-Headers $\rightarrow$ Antwort an MAC-Adresse kann mittels IP-Unicast realisiert werden
```
nehme ich mal an

2020-12-10 18:24 UTC, RvNovae commented on NET/README.md
> +    - Spanning-Tree weiss nichts von VLANS, also kein Spannbaum pro VLAN
```suggestion
    - Spanning-Tree weiss nichts von VLANs, also kein Spannbaum pro VLAN
```

2020-12-10 18:24 UTC, RvNovae commented on NET/README.md
> +- **mögliches Prüfungsszenario: Beschreibung der Einrichtung eines VLAN´s á la Probeklausur**
```suggestion
- **mögliches Prüfungsszenario: Beschreibung der Einrichtung eines VLANs á la Probeklausur**
```

2020-12-10 18:24 UTC, RvNovae commented on NET/README.md
> +  - Ressource-Records (insbesondere A-Level-Records) werden dann auf dem NS des Hosters hinterlegt
```suggestion
  - Resource-Records (insbesondere A-Level-Records) werden dann auf dem NS des Hosters hinterlegt
```

2020-12-10 18:24 UTC, RvNovae commented on NET/README.md
> +  - Abfolgen von Calls bei Socketaufrufen und deren Funktion
```suggestion
  - Abfolgen von Calls bei Socketaufrufen und deren Funktion
  - Raw-Sockets einordnen können (wofür notwendig); darüber hinaus nicht relevant
```

2020-12-11 07:10 UTC, sthinbetween commented on NET/README.md
> +3. VTEP der physischen Maschine, die die adressierte VM ausführt, nimmt UDP-Paket entgegen und entfernt die ergänzten Header, so dass nur das ursprüngliche Ethernet-Frame bleibt
stimmt schon so wie es ist :)

2020-12-11 07:13 UTC, sthinbetween commented on NET/README.md
> +  - Abfolgen von Calls bei Socketaufrufen und deren Funktion
sicher?

2020-12-11 07:17 UTC, sthinbetween commented on NET/README.md
> +- VTEP speichert eine Abbildung der Quell-MAC-Adresse des gekapselten Ethernet-Frames und der Quell-IP-Adresse des kapselnden IP-Headers $\rightarrow$ Antwort an MAC-Adresse kann mittels IP-Unicast r
auch hier glaube ich, dass es schon richtig ist wie er es geschrieben hat. Weil es hier ja wikrlich um den kapselnden, also den umschließenden Header geht. In Abgrenzung zum gekapselten, also umschlossenenen Ethernet-Frame

2020-12-11 10:13 UTC, RvNovae commented on NET/README.md
> +3. VTEP der physischen Maschine, die die adressierte VM ausführt, nimmt UDP-Paket entgegen und entfernt die ergänzten Header, so dass nur das ursprüngliche Ethernet-Frame bleibt
aaaa die kommata, naja gut 😅

2020-12-11 10:14 UTC, RvNovae commented on NET/README.md
> +- VTEP speichert eine Abbildung der Quell-MAC-Adresse des gekapselten Ethernet-Frames und der Quell-IP-Adresse des kapselnden IP-Headers $\rightarrow$ Antwort an MAC-Adresse kann mittels IP-Unicast r
Ahhh okay, dann passts natürlich

2020-12-11 10:14 UTC, RvNovae commented on NET/README.md
> +  - Abfolgen von Calls bei Socketaufrufen und deren Funktion
Bin mir ziemlich sicher, dass er das gesagt hat.

2020-12-11 10:45 UTC, RvNovae approved these changes

2020-12-11 16:05 UTC, ZeroPointMax approved these changes
🎸

2020-12-12 09:40 UTC, merged