DBS PIA 06.10.2020: added ERM/schema sample from today's lecture
importPI19fromDHGE/dhge-pi19-sem3 pull request #2
Opened 2020-10-06 12:44 UTC by ZeroPointMax

To illustrate database schemas, i made a simple SVG in Inkscape.

2020-10-06 13:13 UTC, Steve2955 requested changes

2020-10-06 13:13 UTC, Steve2955 commented on DBS/README.md
> +	- ![Beispiel-ERM: Menschen sind Halter von Fahrzeugen](./resources/erm-bsp.svg)
Der Pfad zum Bild funktioniert hier auf GH leider nicht so. Ich verwende daher in der Regel den Link zu GH-Pages. Das funktioniert allerdings leider erst, wenn die Datei auch auf der ```main```-branch ist 😅

[https://importpi19fromdhge.github.io/dhge-pi19-sem3/DBS/resources/erm-bsp.svg](https://importpi19fromdhge.github.io/dhge-pi19-sem3/DBS/resources/erm-bsp.svg)

Alternative wäre ein Link zur RAW-Ansicht der Datei: 

[https://raw.githubusercontent.com/importPI19fromDHGE/dhge-pi19-sem3/1481311b7c844ef9ba306baee28b34c7b98f273f/DBS/resources/erm-bsp.svg](https://raw.githubusercontent.com/importPI19fromDHGE/dhge-pi19-sem3/1481311b7c844ef9ba306baee28b34c7b98f273f/DBS/resources/erm-bsp.svg)

Ich persönlich bevorzuge Ersteres.

2020-10-06 14:48 UTC, ZeroPointMax commented on DBS/README.md
> +	- ![Beispiel-ERM: Menschen sind Halter von Fahrzeugen](./resources/erm-bsp.svg)
Oh echt? Mir wird das Bild in der Branch korrekt angezeigt? Ist ja doof 😅

2020-10-06 16:44 UTC, ZeroPointMax commented on DBS/README.md
> +	- ![Beispiel-ERM: Menschen sind Halter von Fahrzeugen](./resources/erm-bsp.svg)
@Steve2955 verstehe ich dich hier falsch? In meinem Fork (hab ihn in meiner unendlichen Genialität schon gelöscht, sorry 🙄 ) habe ich das Bild gesehen? Oder meinst du, dass GitHub-Pages dann nicht funktioniert?

2020-10-07 08:00 UTC, Steve2955 commented on DBS/README.md
> +	- ![Beispiel-ERM: Menschen sind Halter von Fahrzeugen](./resources/erm-bsp.svg)
nvm scheint doch zu funktionieren, weiß nicht warum ich mich in der Vergangenheit so blöd angestellt habe 😅

2020-10-07 08:00 UTC, Steve2955 approved these changes

2020-10-07 08:01 UTC, merged

2020-10-07 08:15 UTC, ZeroPointMax commented on DBS/README.md
> +	- ![Beispiel-ERM: Menschen sind Halter von Fahrzeugen](./resources/erm-bsp.svg)
LOL 😂