DBS Praktikum: SQL Basics
importPI19fromDHGE/dhge-pi19-sem3 pull request #31
Opened 2020-11-03 16:06 UTC by Steve2955

2020-11-03 16:06 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/DBS/praktikum/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/DBS/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/PRO/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/RES/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/SWE/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- DBS/praktikum/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2020-11-03 18:03 UTC, ZeroPointMax requested changes
Eine Anmerkung bei den Gleitkommazahlen, ansonsten würde ich mir nur noch Kommentare an den SQL-Befehlen wünschen, etwa so:

```sql
use ker_bibliothek;
go
/*go f�hrt das oben aus*/

create table Buch (
	id bigint PRIMARY KEY, /*Spalte ID vom Typ BigInt, Prim�rschl�ssel*/
	isbn13 char(14) UNIQUE, /*darf nicht doppelt vorkommen*/
	seiten int DEFAULT(110), /*wenn nichts angegeben, dann 110 Seiten*/
	titel nvarchar(100) NOT NULL, /*variabler Speicherplatz, aber maximal 100 Zeichen. Darf nicht leer sein*/
	preis real, /*entspricht float(24), s. MS Docs*/
	);
```

```sql
create database ker_bibliothek
ON PRIMARY(Name = 'Ker_Bibliothek' /*logischer Name*/, Filename = N'C:\DHGE\Datenbankuebung\Bibliothek.mdf' /*Dateipfad UTF-8 kodiert mit N-Pr�fix; Optional*/,
           SIZE = 20MB, Filegrowth = 5% /*geht auch absolut*/)
LOG ON (Name = 'Ker_Bibo_Log', Filename = N'c:\DHGE\Datenbankuebung\Bibliothek.ldf',
		Size = 10MB, Filegrowth=1MB, MAXSIZE=100MB /*Achtung: sobald voll, kann man keine �nderungen mehr machen*/);
```

Ansonsten sehr schöne Mitschriften 👍

2020-11-04 07:03 UTC, Steve2955 commented on DBS/praktikum/README.md
> +| `float, double`                 | Gleitkommazahlen                                      |
Klar, mein Fehler. Ich konnte während seiner Präsentation nicht alles mitschreiben und da er sie noch nicht auf BAckstage gestellt hatte, habe ich mich blöderweise an die falsche Quelle gewandt. Schön das alles standardisiert ist😅

2020-11-04 07:05 UTC, ZeroPointMax commented on DBS/praktikum/README.md
> +| `float, double`                 | Gleitkommazahlen                                      |
Ja, jede Implementierung ist anders 😅

2020-11-04 07:07 UTC, Steve2955 commented
@ZeroPointMax Ich persönlich finde wir sollten das mit den Kommentaren nicht zu sehr übertreiben. Die Attribute selbst sind ja schon ziemlich aussagekräftig und da ich sie zusätzlich nochmal kurz in der Tabelle beschrieben habe, ist das aus meiner Sicht nicht nötig.

2020-11-04 08:39 UTC, ZeroPointMax commented
Fair Point, die Tabelle gibt nochmal Aufschlüsse.
Ich hab für meinen Part Kommentare lieber gleich in der Zeile, aber das läuft dann auf persönliche Präferenz hinaus.

2020-11-04 08:39 UTC, ZeroPointMax approved these changes
s.o.

2020-11-04 09:28 UTC, merged