Mitschriften SWE 09.11.2020
importPI19fromDHGE/dhge-pi19-sem3 pull request #42
Opened 2020-11-09 14:18 UTC by RvNovae

2020-11-09 14:18 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/SWE/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/DBS/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/DBS/praktikum/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/PRO/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/RES/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- SWE/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2020-11-09 18:07 UTC, ZeroPointMax requested changes
ein kleiner Rechtschreibfehler, ansonsten sehr schöne Mitschriften :-) 👍

2020-11-09 18:07 UTC, ZeroPointMax commented on SWE/README.md
> +- Erklärung eines Fteaures aus Sicht einer Person, die dieses Feature verwenden will
Features*

2020-11-09 18:14 UTC, RvNovae commented on SWE/README.md
> +- Erklärung eines Fteaures aus Sicht einer Person, die dieses Feature verwenden will
Oh ja, danke haha

2020-11-10 07:31 UTC, ZeroPointMax approved these changes
👍

2020-11-10 07:41 UTC, merged