FIX: Images in PDFs
importPI19fromDHGE/dhge-pi19-sem3 pull request #56
Opened 2020-11-17 11:14 UTC by Steve2955

Should resolve #54

2020-11-17 12:37 UTC, ZeroPointMax commented on DBS/README.md
> +![zusätzliche Begriffe aus dem Video](resources/db_begriffe_screenshot.png){ width=500px }
Oh. So geht das also :D

2020-11-17 12:41 UTC, ZeroPointMax requested changes
![image](https://user-images.githubusercontent.com/26359277/99391392-6d7fb680-28da-11eb-9114-ea9ae72f0897.png)

{ width = xyz } geht offenbar nicht ;)
bzw. geht es nur im Pandoc, da habe ich noch nicht nachgesehen

2020-11-17 12:49 UTC, Steve2955 commented
> bzw. geht es nur im Pandoc, da habe ich noch nicht nachgesehen

Stimmt das geht nur in `pandoc`, sonst werden die Bilder auf die komplette Seitenbreite gezogen, was oft sehr unschön aussieht.

2020-11-17 12:51 UTC, Steve2955 commented on DBS/README.md
> +![zusätzliche Begriffe aus dem Video](resources/db_begriffe_screenshot.png){ width=500px }
In `pandoc` ja, auf Github funktioniert nur die HTML-Syntax für Bilder mit Breitenangabe

2020-11-18 15:23 UTC, Steve2955 commented
@ZeroPointMax Würdest du dich dazu bereiterklären, wie gestern besprochen, ein kleines Skript zu schreiben oder wollen wir diese Einschränkung in Kauf nehmen?

Wenn ja können wir die gewünschte Größe eventuell als HTML-Kommentar hinter das `![]()` schreiben, damit man weiterhin Einfluss auf die Größe der einzelnen Bilder nehmen kann, ohne das wir die Darstellung auf Github beeinflussen? Also etwa so:

```markdown
![Example](example.png)<!-- width = 500px-->
```

2020-11-18 19:18 UTC, ZeroPointMax commented
ich kann nichts versprechen, werde das aber mal untersuchen :+1:

2020-11-20 21:01 UTC, Steve2955 commented
@ZeroPointMax Ich bin jetzt kein Experte und man kann das sicher noch viel schöner lösen, aber würde folgendes nicht funktionieren? 😅 

```bash
 awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{print}' input >> output
```

2020-11-25 10:40 UTC, closed without merging