NET sthinbetween 20201126
importPI19fromDHGE/dhge-pi19-sem3 pull request #78
Opened 2020-11-26 15:31 UTC by sthinbetween

oof

2020-11-26 15:31 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/NET/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/DBS/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/RES/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/PRO/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/SWE/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- NET/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2020-11-26 15:35 UTC, RvNovae approved these changes
wow 🤯

2020-11-26 15:52 UTC, Steve2955 requested changes
Ich habe auch Mitschriften zu `NET` gemacht, die würde ich heute Abend oder morgen noch hier rein mergen

2020-11-26 17:11 UTC, Steve2955 commented on NET/README.md
> +# 3 Internetprotokoll und Hilfsprotokolle
@ZeroPointMax  @RvNovae  @sthinbetween 

Wollen wir wirklich eine Nummerierung in den Überschriften? 

*Persönlich hätte ich sie nicht ergänzt, weil Herr Feldmann auch keine auf seinen Folien benutzt.*

2020-11-26 17:16 UTC, RvNovae commented on NET/README.md
> +# 3 Internetprotokoll und Hilfsprotokolle
Mir eigentlich relativ egal.
In SWE hab ich sie immer weggelassen.

2020-11-26 18:57 UTC, ZeroPointMax commented on NET/README.md
> +# 3 Internetprotokoll und Hilfsprotokolle
Ich tendiere sehr gerne dazu, die irgendwann sowieso zu vergessen, weshalb ich die am liebsten konsequent weglasse

2020-11-26 19:05 UTC, ZeroPointMax reviewed
@sthinbetween dude, wie kriegst du das so gut hin? :1st_place_medal: 

Da pushe ich meine Mitschriften nicht, deine sind besser und dem habe ich nichts mehr hinzuzufügen :D
Was ich hinzufügen möchte, ist eine kleine Doc von dem was ich heute nochmal vorgestellt habe, natürlich ist an der Stelle nochmal @nukerxy auch sehr viel Credit zu geben!

2020-11-26 19:24 UTC, ZeroPointMax requested changes
@sthinbetween ich würde gerne #79 rekursiv mergen, ansonsten - wie gesagt - astreine Mitschriften

2020-11-26 19:27 UTC, sthinbetween commented
Danke für die Props,
macht mit dem PR was ihr wollt. Mein Zutun ist ja nicht unbedingt erforderlich, oder?

2020-11-26 19:31 UTC, ZeroPointMax commented
@sthinbetween naja ist ja immer noch deine Branch ^^

Danke für den Merge :+1:

2020-11-26 19:32 UTC, ZeroPointMax approved these changes

2020-11-26 19:34 UTC, sthinbetween commented
> @sthinbetween naja ist ja immer noch deine Branch ^^
> 
> 
> 
> Danke für den Merge :+1: 

Was weiß ich denn, wie das mit den Rechten funktioniert hier ;) 
Was Git betrifft entferne ich mich nur mit BabySteps vom Noobdasein.

2020-11-26 19:38 UTC, ZeroPointMax commented
> > @sthinbetween naja ist ja immer noch deine Branch ^^
> > Danke für den Merge +1
> 
> Was weiß ich denn, wie das mit den Rechten funktioniert hier ;)
> Was Git betrifft entferne ich mich nur mit BabySteps vom Noobdasein.

Keine Sorge, hier weiß keiner, was er tut :D

2020-11-27 08:03 UTC, Steve2955 commented on NET/README.md
> +  - der Empfänger informiert dann über TCP-Header den Sender
Der Empfänger ist hier der Empfänger der Rückmeldung, also der Sender des ursprünglichen Pakets, und der Sender ist der Sender der Rückmeldung, richtig?

2020-11-27 10:53 UTC, Steve2955 approved these changes

2020-11-27 14:10 UTC, merged