RES: Prüfungsfragen mit Antworten
importPI19fromDHGE/dhge-pi19-sem3 pull request #81
Opened 2020-11-27 15:40 UTC by ZeroPointMax

...in neuer Datei, damit man sie nicht sofort sieht.

Vielen Dank an @Mindwing-cmd fürs notieren!

2020-11-28 08:43 UTC, Steve2955 requested changes
Vielen Dank für die PR. Zum Ende hin wird es etwas oberflächlich, ich denke da sollten wir noch ein paar Sachen ändern.

2020-11-28 08:43 UTC, Steve2955 commented on RES/pruefungsfragen.md
> +  - Datenspiegelung = Datenkopie auf dem selben System
In zwingendes Kriterium für die Datenspiegelung ist doch, das diese auf unterschiedlichen Laufwerken erfolgt, das sollten man hier noch erwähnen.

2020-11-28 08:43 UTC, Steve2955 commented on RES/pruefungsfragen.md
> +  - Bandbreit = Maximum der Datenrate
Meines Wissens nach ist die Bandbreite der Frequenzbereich über den die Kommunikation erfolgt

2020-11-28 08:43 UTC, Steve2955 commented on RES/pruefungsfragen.md
> +  - Datenrate = aktuelle Menge der übertragenen Daten
*Menge der übertragenen Daten in einem bestimmten Zeitraum* trifft es meiner Meinung nach besser

2020-11-28 08:43 UTC, Steve2955 commented on RES/pruefungsfragen.md
> +  - Key
So wie ich den Günther kenne, legt er viel Wert auf Genauigkeit, also passt hier vielleicht *Private Key dessen Public Key Pair in den `authorized_keys` des entsprechenden Servers vorhanden ist* besser

2020-11-28 08:43 UTC, Steve2955 commented on RES/pruefungsfragen.md
> +  - Testumgebung
Isolation; mehrere getrennte Systeme auf einem Host

2020-11-30 07:32 UTC, ZeroPointMax commented on RES/pruefungsfragen.md
> +  - Datenspiegelung = Datenkopie auf dem selben System
Ja. Wenn wir schon dabei sind - evtl auch erwähnen, dass eine Sicherung - ob kalt oder heiß - unabhängig von zukünftigen Änderungen am Quellsystem bspw. durch einen Krypto-Trojaner ist (bzw. sein sollte)?

2020-11-30 07:40 UTC, ZeroPointMax commented on RES/pruefungsfragen.md
> +  - Bandbreit = Maximum der Datenrate
Grundsätzlich ja, aber hier laufen wir in Begriffs-Schwierigkeiten. Es gibt Leiter, die keine klassische Bandbeite haben - z.B. Multi-Channel Glasfaser. Die haben zwar einen Frequenzbereich, aber die Position des Lichts beim Ein-/Austreten ist auch relevant. Etc.
Daher der vage Begriff

2020-11-30 08:11 UTC, Steve2955 commented on RES/pruefungsfragen.md
> +  - Bandbreit = Maximum der Datenrate
Habt ihr (PIA) diese Prüfungsfrage mit Herr Günther besprochen? Er hat bei uns sehr viel Wert auf diese Unterscheidung gelegt und darauf das die Bandbreite erstmal nichts mit der Datenübertragungsrate zu tun hat. Also ja, die Bandbreite begrenzt in irgendeiner Art das Maximum der Datenübertragungsrate, aber nach Herr Günther ist dieser Begriff hier allein als physikalische Kenngröße zu betrachten.

2020-11-30 08:11 UTC, nukerxy requested changes
ansonsten i.O. :) Danke!

2020-11-30 08:11 UTC, nukerxy commented on RES/pruefungsfragen.md
> +  - >> An File anfügen
Anzeige: ">" und ">>" ohne Anführungszeichen sind reserviert; sieht nicht gut aus

2020-11-30 08:11 UTC, nukerxy commented on RES/pruefungsfragen.md
> +  - Bandbreit = Maximum der Datenrate
Bandbreit**e**

2020-11-30 08:19 UTC, nukerxy commented on RES/pruefungsfragen.md
> +  - Bandbreit = Maximum der Datenrate
Haben wir nicht besprochen. Seine Beschreibung von Bandbreite ist die ursprüngliche, physikalische Bedeutung. Leider wird der Begriff auch oft falsch für Datenrate verwendet, daher waren wir unschlüssig.

2020-11-30 08:19 UTC, ZeroPointMax commented on RES/pruefungsfragen.md
> +  - Bandbreit = Maximum der Datenrate
Nicht, dass ich mich erinnern würde...

Dann würde ich es ändern in "Frequenzbereich, über den Kommunikation erfolgt"

2020-11-30 08:22 UTC, nukerxy approved these changes

2020-11-30 08:26 UTC, Steve2955 approved these changes
Vielen Dank @ZeroPointMax 👍

2020-11-30 10:23 UTC, merged