Res max 20201201
importPI19fromDHGE/dhge-pi19-sem3 pull request #86
Opened 2020-12-01 10:32 UTC by ZeroPointMax

nur Vorträge und Langeweile heute

2020-12-01 10:33 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/RES/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/NET/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/DBS/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/PRO/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/SWE/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed 2 files: </summary>

- NET/README.md
- RES/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2020-12-01 17:14 UTC, nukerxy commented on RES/README.md
> +  - Sicherung:(){ :|:& };:
?

2020-12-01 17:25 UTC, Steve2955 commented on RES/README.md
> +  - Sicherung:(){ :|:& };:
Sieht aus wie eine Fork Bomb, aber keine Ahnung wie die da hin kommt 😅

2020-12-01 19:56 UTC, Steve2955 requested changes

2020-12-01 19:56 UTC, Steve2955 commented on RES/README.md
> +```
Fehlt hier noch was?

2020-12-01 20:24 UTC, ZeroPointMax commented on RES/README.md
> +```
Ahja, Benedict kann/will sein Skript nicht veröffentlichen, weil ein Kollege ihm geholfen hat und er nicht nachgefragt hat, ob er das darf

2020-12-01 20:25 UTC, ZeroPointMax commented on RES/README.md
> +  - Sicherung:(){ :|:& };:
OH NO! WEG DAMIT!

Hintergrund: Ich habe bei Linux das "Feature", dass ich die mittlere Trackpoint-Taste zum pasten drücken kann. Die wird aber auch zum scrollen benutzt. Daher habe ich es aus Versehen eingefügt :/

2020-12-01 20:28 UTC, ZeroPointMax commented on RES/README.md
> +```
...das will er noch klären, bis dahin würde ich die Codebox-Leiche wegmachen

2020-12-02 07:20 UTC, Steve2955 approved these changes

2020-12-02 07:30 UTC, nukerxy approved these changes

2020-12-03 10:07 UTC, merged