DBS-Praktikum: DLL-Trigger, Stored Procedures
importPI19fromDHGE/dhge-pi19-sem3 pull request #87
Opened 2020-12-02 07:31 UTC by Steve2955

Wir haben die Themen heute wirklich nur kurz besprochen, mehr Hintergrundinfos gab es nicht. Ich schätze mal die Themen haben keine große Bedeutung für die Klausur.

2020-12-02 07:32 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/NET/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/DBS/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/RES/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/PRO/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/SWE/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- NET/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2020-12-03 10:09 UTC, ZeroPointMax requested changes
- siehe Kommentar unten
- Hmm ich hab gestern schon was commitet, aber keine PR gemacht. Evtl können wir was mergen

2020-12-03 10:09 UTC, ZeroPointMax commented on DBS/praktikum/README.md
> +### `DLL`-Trigger
Heißt es nicht "Data Definition Language" und er spricht es falsch aus?

2020-12-03 10:09 UTC, RvNovae approved these changes
Ich glaube zwar eher, dass die Sachen aus Zeitgründen nur so kurz behandelt wurden, aber ein Fokus wird darauf in der Klausur wahrscheinlich nicht gelegt werden.

Danke für die schöne Übersicht :)

2020-12-03 10:11 UTC, RvNovae commented on DBS/praktikum/README.md
> +### `DLL`-Trigger
Stimmt, es sollte `DDL`-Trigger heißen.

2020-12-03 10:12 UTC, Steve2955 commented on DBS/praktikum/README.md
> +### `DLL`-Trigger
Stimmt hat `DDL` wäre richtig, hat er das wirklich falsch gesagt oder habe ich mich nur verschrieben?

2020-12-03 10:14 UTC, Steve2955 commented
@ZeroPointMax kannst ja einfach mal eine PR auf diese Branch machen und wir mergen deine Mitschriften noch hier rein👍

2020-12-03 17:56 UTC, ZeroPointMax commented on DBS/praktikum/README.md
> +### `DLL`-Trigger
Er sagt es jedes Mal falsch :D

2020-12-04 10:13 UTC, ZeroPointMax approved these changes

2020-12-04 10:13 UTC, merged