SWE-sthinbetween-20201203
importPI19fromDHGE/dhge-pi19-sem3 pull request #92
Opened 2020-12-03 10:07 UTC by sthinbetween

Meh.

2020-12-03 10:10 UTC, Steve2955 requested changes
Vielen Dank für die Mitschriften. Ich würde den Merge wieder übernehmen.

2020-12-03 10:19 UTC, ZeroPointMax commented
> Meh.

Meh.

2020-12-04 06:33 UTC, Steve2955 requested changes
Nach einem merge mit #94 kann ich die PR approven

2020-12-04 06:38 UTC, Steve2955 approved these changes

2020-12-04 06:45 UTC, ZeroPointMax approved these changes

2020-12-04 06:45 UTC, merged