PRO-sthinbetween-20201204
importPI19fromDHGE/dhge-pi19-sem3 pull request #97
Opened 2020-12-04 13:28 UTC by sthinbetween

War nicht besonders viel heute, leider ja auch wieder unstrukturiert vorgetragen. 
Habe mal die Abbildungen in draw.io umgesetzt, falls euch da noch Fehler auffallen kann ich die nochmal ändern. 
Wie verhält es sich denn mit LaTex in den Markdowns? -> siehe Kommentar.

2020-12-04 13:29 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/PRO/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/DBS/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/RES/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/SWE/README.md
  - /home/runner/work/dhge-pi19-sem3/dhge-pi19-sem3/NET/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- PRO/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2020-12-04 13:57 UTC, RvNovae commented
Die Mathe-LaTeX sachen gehen auf jeden fall, wenn du inline `$1\leg2...$` und bei Blöcken mit doppelten `$$ <mehrere zeilen>$$` machst 😃 Also wie in LaTeX auch mit Dollar Zeichen delimited.

2020-12-04 14:00 UTC, RvNovae requested changes
see comment above

2020-12-04 14:03 UTC, RvNovae commented
Jetzt siehts an der Stelle richtig aus :)

2020-12-05 15:51 UTC, ZeroPointMax approved these changes
👍

2020-12-06 19:05 UTC, RvNovae approved these changes

2020-12-06 19:05 UTC, RvNovae commented on PRO/README.md
> +<!-- TODO: Können wir LaTex und wenn ja, wie? -->
```suggestion

```

2020-12-07 06:40 UTC, merged